App:
  Name: basic-backend
  Host: localhost
  Port: 13271

Logger:
  Level: Info

Database:
  Host: mysql
  Port: "%d"
  Username: "%s"
  Password: "%s"
  Name: "%s"

  MaxIdleConns: 10
  MaxOpenConns: 100
  ConnMaxLifetime: 3600

Redis:
  Host: redis
  Port: 6379
  Password: "%s"